### ISSUE TITLE
When numbers only given in trafficsplit weight returns `0`

### ISSUE THREAD

**Issue by surajssd** [deislabs/smi-adapter-istio#12]
For the following TrafficSplit object the VirtualService is never updated because of following error:

```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: reviews-rollout
spec:
  service: reviews
  backends:
  - service: reviews-v1
    weight: 0
  - service: reviews-v2
    weight: 1000
```

error in operator

```json
{"level":"info","ts":1557923491.9240608,"logger":"controller_trafficsplit","msg":"Reconciling TrafficSplit",
"Request.Namespace":"smi-demo","Request.Name":"reviews-rollout"}
{"level":"info","ts":1557923491.9241369,"logger":"controller_trafficsplit","msg":"------> giving weight:",
"Request.Namespace":"smi-demo","Request.Name":"reviews-rollout","reviews-v1":0}
{"level":"info","ts":1557923491.9241776,"logger":"controller_trafficsplit","msg":"------> giving weight:",
"Request.Namespace":"smi-demo","Request.Name":"reviews-rollout","reviews-v2":0}
{"level":"info","ts":1557923491.9244137,"logger":"controller_trafficsplit","msg":"Updating VirtualService",
"Request.Namespace":"smi-demo","Request.Name":"reviews-rollout","VirtualService.Namespace":"smi-demo","VirtualService.Name":"reviews-rollout-vs"}
{"level":"error","ts":1557923491.9342525,"logger":"kubebuilder.controller","msg":"Reconciler error",
"controller":"trafficsplit-controller","request":"smi-demo/reviews-rollout",
"error":"admission webhook \"pilot.validation.istio.io\" denied the request: configuration is invalid: total destination weight 0 != 100","stacktrace":"github.com/deislabs/smi-adapter-istio/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/deislabs/smi-adapter-istio/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/deislabs/smi-adapter-istio/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/surajd/go/src/github.com/deislabs/smi-adapter-istio/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

This somewhere related to the object code in the function:

```go
func quantityToKilo(q resource.Quantity) int {
	// TODO: reuse existing resource.Quantity methods to get the amount
	numberBytes, suffixBytes := q.CanonicalizeBytes(make([]byte, 18, 18))
	number := strings.Trim(string(numberBytes), "\000")
	suffix := strings.Trim(string(suffixBytes), "\000")
	out, _ := strconv.Atoi(number)
	if suffix == "m" {
		return out
	} else if suffix == "" {
		return out * 1000
	} else {
		return 0
	}
}
```

But if the TrafficSplit object is changed to following things work just fine.

```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: reviews-rollout
spec:
  service: reviews
  backends:
  - service: reviews-v1
    weight: "0m"
  - service: reviews-v2
    weight: "1000m"
```
