### ISSUE TITLE
Implementing HTTPRouteGroup and TrafficTarget for Istio

### ISSUE THREAD

**Issue by surajssd** [deislabs/smi-adapter-istio#18]
For the given SMI configs:

```yaml
apiVersion: specs.smi-spec.io/v1alpha1
kind: HTTPRouteGroup
metadata:
  name: api-service-routes
matches:
- name: api
  pathRegex: /api
  methods: ["*"]
- name: metrics
  pathRegex: /metrics
  methods: ["GET"]

---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: api-service-metrics
  namespace: default
destination:
  kind: ServiceAccount
  name: api-service
  namespace: default
specs:
- kind: HTTPRouteGroup
  name: api-service-routes
  matches:
  - metrics
sources:
- kind: ServiceAccount
  name: prometheus
  namespace: default

---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: api-service-api
  namespace: default
destination:
  kind: ServiceAccount
  name: api-service
  namespace: default
  port: 8080
specs:
- kind: HTTPRouteGroup
  name: api-service-routes
  matches:
  - api
sources:
- kind: ServiceAccount
  name: website-service
  namespace: default
- kind: ServiceAccount
  name: payments-service
  namespace: default
```

From what I understand can be converted to following istio configs:

```yaml
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: api-service-metrics
  namespace: default
spec:
  rules:
  - services: ["*"]
    paths: ["/metrics"] # from HTTPRouteGroup.matches.pathRegex
    methods: ["GET"]    # from HTTPRouteGroup.matches.methods
    constraints:
    - key: "destination.user"
      values: ["api-service"]       # from TrafficTarget.destination.name
    - key: "destination.namespace"
      values: ["default"]           # from TrafficTarget.destination.namespace
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: api-service-metrics
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/prometheus"   # from TrafficTarget.sources.name
  roleRef:
    kind: ServiceRole
    name: "api-service-metrics"


---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: api-service-api
  namespace: default
spec:
  rules:
  - services: ["*"]
    paths: ["/api"]     # from HTTPRouteGroup.matches.pathRegex
    methods: ["*"]      # from HTTPRouteGroup.matches.methods
    constraints:
    - key: "destination.port"
      values: ["8080"]              # from TrafficTarget.destination.port
    - key: "destination.user"
      values: ["api-service"]       # from TrafficTarget.destination.name
    - key: "destination.namespace"
      values: ["default"]           # from TrafficTarget.destination.namespace
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: api-service-api
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/website-service"     # from TrafficTarget.sources.name
  - user: "cluster.local/ns/default/sa/payments-service"    # from TrafficTarget.sources.name
  roleRef:
    kind: ServiceRole
    name: "api-service-api"
```

### How is this conversion done?

* Here pair of Istio `ServiceRole` and Istio `ServiceRoleBinding` is created with same name based on each SMI `TrafficTarget`. For the SMI `HTTPRouteGroup` referred in SMI `TrafficTarget.specs.kind` a corresponding Istio `ServiceRole` is created.

* For each SMI `TrafficTarget.specs[*].matches.pathRegex` & `TrafficTarget.specs[*].matches.methods` list the entries in corresponding Istio `ServiceRole.spec.rules.paths` & `ServiceRole.spec.rules.methods` respectively will be populated.

* For each SMI `TrafficTarget.sources` the service account names are just put into Istio `ServiceRoleBinding.spec.subjects`.

* For each SMI `TrafficTarget.destination.name` the entry is added to Istio `ServiceRole.spec.rules.constraints` with key as `destination.user` and similarly for the namespace and port information is added.
