### ISSUE TITLE
weight logic clarification

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-adapter-istio#61]
Istio only talks about weights as whole numbers (0-100) that indicate percentage traffic and in the documentation never mentions the milli notation ("1000m"). The docs also state that the weights should add up to 100. 

Is there a reason to support the milli notation? or should we switch to only supporting whole numbers?

**Comment by grampelberg** [comment]
Whole numbers makes sense, I would like to stay away from having it all add up to 100. Percentages imply some things that might not actually happen and cause confusion for users.

**Comment by michelleN** [comment]
I'm good with the numbers not having to add up to 100. That is an Istio specific implementation detail and shouldn't apply across the board.

**Comment by olix0r** [comment]
For context, the intent was the mirror the CPU request/limit API, because they seem like pretty similar things when you get into it, especially if we consider how rate limiting may layer onto this in the future...  A weight of 100m imples "give me 10% of my alotted load."

There's no master plan here, though. It just felt like an opportunity to leverage an existing resource-allocation model in K8s.

**Comment by michelleN** [comment]
Thanks for the context @olix0r. I get where ya'll are going with this. I just think we're lacking the right docs. For example, what happens if 1 service has a weight of 100m but the other service has nothing defined. Does that mean the other service gets 90% of the traffic without have to explicitly define that in the yaml?

So if we go the route of whole numbers and not requiring the total be 100 (and therefore getting rid of the fact that these weights are percents), then weights would work as follows:

`Scenario 1`
```
backends:
- service: service-a
   weight: 500
- service: service-b
   weight: 1000
```
In Scenario 1, `service-a` gets .33.33% of traffic and  `service-b` gets 66.66%.

`Scenario 2`
```
backends:
- service: service-a
   weight: 10
- service: service-b
   weight: 100
- service: service-c
   weight: 1500
```
In Scenario 3, `service-a` gets .0.62% of traffic, `service-b` gets 6.21% of traffic and `service-c` gets 93.17% of traffic

`Scenario 3`
```
backends:
- service: service-a
   weight: 1
- service: service-b
   weight: 0
```
In Scenario 3, `service-a` gets 100% of traffic and `service-b` gets 0%.

@grampelberg - is this how you're thinking about weights? I also want to make sure we're not doing something completely out there. Curious to know how you would translate these numbers in the linkerd world.
